name: update-flake-lock
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch: # Allow manual triggering

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock and Push
        run: |
          nix flake update
          git config --global user.name 'Mio'
          git config --global user.email 'mio@mio19.uk'
          git add flake.lock
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update flake.lock"
            git push
          fi
